apiVersion: v1
kind: Service
metadata:
  name: ecom-product-service
spec:
  selector:
    app: ecom-product-service
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30281
  type: NodePort